const ROUTES = [
 {
   "route_id": "APS_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "City Circle to Macarthur via Airport",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_1b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "City Circle to Leppington via Airport",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_1c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "City Circle to Macarthur via Sydenham",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_1d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "City Circle to Macarthur via Sydenham",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_1e",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "City Circle to Leppington via Sydenham",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_1f",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "City Circle to Leppington via Sydenham",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_2a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "Macarthur to City Circle via Airport",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_2b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "Leppington to City Circle via Airport",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_2c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "Macarthur to City Circle via Sydenham",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_2d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "Macarthur to City Circle via Sydenham",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_2e",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "Leppington to City Circle via Sydenham",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "APS_2f",
   "agency_id": "SydneyTrains",
   "route_short_name": "T8",
   "route_long_name": "Leppington to City Circle via Sydenham",
   "route_desc": "T8 Airport & South Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BMT_1",
   "agency_id": "NSWTrains",
   "route_short_name": "BMT",
   "route_long_name": "Central to Lithgow and Bathurst",
   "route_desc": "Blue Mountains Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BMT_2",
   "agency_id": "NSWTrains",
   "route_short_name": "BMT",
   "route_long_name": "Bathurst and Lithgow to Sydney",
   "route_desc": "Blue Mountains Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "City Circle to Lidcombe via Bankstown",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_1b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "City Circle to Lidcombe via Bankstown",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_1c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Regents Park to Lidcombe",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_1d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "City Circle to Liverpool via Bankstown",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_1e",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "City Circle to Liverpool via Bankstown",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_1f",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "City Circle to Liverpool via Lidcombe",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_1g",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "City Circle to Liverpool via Lidcombe",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_1h",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Lidcombe to Liverpool",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_2a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Lidcombe to City Circle via Bankstown",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_2b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Lidcombe to City Circle via Bankstown",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_2c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Lidcombe to Regents Park",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_2d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Liverpool to City Circle via Bankstown",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_2e",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Liverpool to City Circle via Bankstown",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_2f",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Liverpool to City Circle via Lidcombe",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_2g",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Liverpool to City Circle via Lidcombe",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "BNK_2h",
   "agency_id": "SydneyTrains",
   "route_short_name": "T3",
   "route_long_name": "Liverpool to Lidcombe",
   "route_desc": "T3 Bankstown Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F37021",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CCN_1a",
   "agency_id": "NSWTrains",
   "route_short_name": "CCN",
   "route_long_name": "Central to Newcastle Interchange via Strathfield",
   "route_desc": "Central Coast & Newcastle Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "D11F2F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CCN_1b",
   "agency_id": "NSWTrains",
   "route_short_name": "CCN",
   "route_long_name": "Central to Newcastle Interchange via North Shore",
   "route_desc": "Central Coast & Newcastle Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "D11F2F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CCN_1c",
   "agency_id": "NSWTrains",
   "route_short_name": "CCN",
   "route_long_name": "Central to Newcastle Interchange via Strathfield",
   "route_desc": "Central Coast & Newcastle Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "D11F2F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CCN_2a",
   "agency_id": "NSWTrains",
   "route_short_name": "CCN",
   "route_long_name": "Newcastle Interchange to Central via Strathfield",
   "route_desc": "Central Coast & Newcastle Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "D11F2F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CCN_2b",
   "agency_id": "NSWTrains",
   "route_short_name": "CCN",
   "route_long_name": "Newcastle Interchange to Central via North Shore",
   "route_desc": "Central Coast & Newcastle Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "D11F2F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CMB_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T5",
   "route_long_name": "Richmond to Leppington",
   "route_desc": "T5 Cumberland Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "C4258F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CMB_1b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T5",
   "route_long_name": "Emu Plains to Leppington",
   "route_desc": "T5 Cumberland Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "C4258F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CMB_1c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T5",
   "route_long_name": "Richmond to Campbelltown",
   "route_desc": "T5 Cumberland Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "C4258F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CMB_1d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T5",
   "route_long_name": "Emu Plains to Campbelltown",
   "route_desc": "T5 Cumberland Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "C4258F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CMB_2a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T5",
   "route_long_name": "Leppington to Richmond",
   "route_desc": "T5 Cumberland Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "C4258F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CMB_2b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T5",
   "route_long_name": "Leppington to Emu Plains",
   "route_desc": "T5 Cumberland Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "C4258F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CMB_2c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T5",
   "route_long_name": "Campbelltown to Richmond",
   "route_desc": "T5 Cumberland Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "C4258F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CMB_2d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T5",
   "route_long_name": "Campbelltown to Emu Plains",
   "route_desc": "T5 Cumberland Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "C4258F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NC1",
   "agency_id": "NSWTrains",
   "route_short_name": "NRC",
   "route_long_name": "Sydney (Central) to Brisbane (Roma Street)",
   "route_desc": "NSW TrainLink North Coast Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NC1a",
   "agency_id": "NSWTrains",
   "route_short_name": "NRC",
   "route_long_name": "Sydney (Central) to Brisbane (Roma Street)",
   "route_desc": "NSW TrainLink North Coast Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NC2",
   "agency_id": "NSWTrains",
   "route_short_name": "NRC",
   "route_long_name": "Brisbane (Roma Street) to Sydney (Central)",
   "route_desc": "NSW TrainLink North Coast Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NW1a",
   "agency_id": "NSWTrains",
   "route_short_name": "NRW",
   "route_long_name": "Sydney (Central) to Moree",
   "route_desc": "NSW TrainLink North Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NW1b",
   "agency_id": "NSWTrains",
   "route_short_name": "NRW",
   "route_long_name": "Sydney (Central) to Armidale",
   "route_desc": "NSW TrainLink North Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NW1c",
   "agency_id": "NSWTrains",
   "route_short_name": "NRW",
   "route_long_name": "Sydney (Central) to Moree",
   "route_desc": "NSW TrainLink North Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NW1d",
   "agency_id": "NSWTrains",
   "route_short_name": "NRW",
   "route_long_name": "Sydney (Central) to Armidale",
   "route_desc": "NSW TrainLink North Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NW2a",
   "agency_id": "NSWTrains",
   "route_short_name": "NRW",
   "route_long_name": "Moree to Sydney (Central)",
   "route_desc": "NSW TrainLink North Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_NW2b",
   "agency_id": "NSWTrains",
   "route_short_name": "NRW",
   "route_long_name": "Armidale to Sydney (Central)",
   "route_desc": "NSW TrainLink North Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1a",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Canberra",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1b",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Canberra",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1c",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Canberra",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1d",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Griffith",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1e",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Griffith",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1f",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Griffith",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1g",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Melbourne",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1h",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Melbourne (Southern Cross)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S1i",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Sydney (Central) to Melbourne (Southern Cross)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2a",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Canberra to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2b",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Canberra to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2c",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Canberra to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2d",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Griffith to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2e",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Griffith to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2f",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Griffith to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2g",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Melbourne (Southern Cross) to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2h",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Melbourne (Southern Cross) to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_S2i",
   "agency_id": "NSWTrains",
   "route_short_name": "STH",
   "route_long_name": "Melbourne (Southern Cross) to Sydney (Central)",
   "route_desc": "NSW TrainLink Southern Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_W1a",
   "agency_id": "NSWTrains",
   "route_short_name": "WST",
   "route_long_name": "Sydney (Central) to Dubbo",
   "route_desc": "NSW TrainLink Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_W1b",
   "agency_id": "NSWTrains",
   "route_short_name": "WST",
   "route_long_name": "Sydney (Central) to Broken Hill",
   "route_desc": "NSW TrainLink Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_W2a",
   "agency_id": "NSWTrains",
   "route_short_name": "WST",
   "route_long_name": "Dubbo to Sydney (Central)",
   "route_desc": "NSW TrainLink Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "CTY_W2b",
   "agency_id": "NSWTrains",
   "route_short_name": "WST",
   "route_long_name": "Broken Hill to Sydney (Central)",
   "route_desc": "NSW TrainLink Western Train Services",
   "route_type": 2,
   "route_url": "",
   "route_color": "F6891F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "Bondi Junction to Waterfall",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_1b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "City Circle to Waterfall",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_1c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "City Circle to Waterfall",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_1d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "Bondi Junction to Cronulla",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_1e",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "City Circle to Cronulla",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_1f",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "City Circle to Cronulla",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_2a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "Waterfall to Bondi Junction",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_2b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "Waterfall to City Circle ",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_2c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "Waterfall to City Circle ",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_2d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "Cronulla to Bondi Junction",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_2e",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "Cronulla to City Circle ",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "ESI_2f",
   "agency_id": "SydneyTrains",
   "route_short_name": "T4",
   "route_long_name": "Cronulla to City Circle ",
   "route_desc": "T4 Eastern Suburbs & Illawarra Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "HUN_1a",
   "agency_id": "NSWTrains",
   "route_short_name": "HUN",
   "route_long_name": "Newcastle to Dungog via Maitland",
   "route_desc": "Hunter Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "833134",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "HUN_1b",
   "agency_id": "NSWTrains",
   "route_short_name": "HUN",
   "route_long_name": "Newcastle to Scone via Maitland",
   "route_desc": "Hunter Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "833134",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "HUN_2a",
   "agency_id": "NSWTrains",
   "route_short_name": "HUN",
   "route_long_name": "Dungog to Newcastle via Maitland",
   "route_desc": "Hunter Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "833134",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "HUN_2b",
   "agency_id": "NSWTrains",
   "route_short_name": "HUN",
   "route_long_name": "Scone to Newcastle via Maitland",
   "route_desc": "Hunter Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "833134",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Parramatta",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Parramatta",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Leppington via Granville",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Leppington via Granville",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1e",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Leppington via Regents Park",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1f",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Leppington via Regents Park",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1g",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Leppington via Bankstown",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1h",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Leppington via Bankstown",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1i",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Campbelltown via Granville",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_1j",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "City Circle to Campbelltown via Granville",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Parramatta to City Circle ",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Parramatta to City Circle ",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Leppington to City Circle via Granville",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Leppington to City Circle via Granville",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2e",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Leppington to City Circle via Regents Park",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2f",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Leppington to City Circle via Regents Park",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2g",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Leppington to City Circle via Bankstown",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2h",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Leppington to City Circle via Bankstown",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2i",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Campbelltown to City Circle via Granville",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "IWL_2j",
   "agency_id": "SydneyTrains",
   "route_short_name": "T2",
   "route_long_name": "Campbelltown to City Circle via Granville",
   "route_desc": "T2 Inner West & Leppington Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "0098CD",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "NSN_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T1",
   "route_long_name": "City to Berowra via Gordon",
   "route_desc": "T1 North Shore Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "NSN_2a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T1",
   "route_long_name": "Berowra and Hornsby to City via Gordon",
   "route_desc": "T1 North Shore Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "NSN_2i",
   "agency_id": "SydneyTrains",
   "route_short_name": "T1",
   "route_long_name": "Berowra to City via Gordon",
   "route_desc": "T1 North Shore Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "NSN_2k",
   "agency_id": "SydneyTrains",
   "route_short_name": "T1",
   "route_long_name": "Berowra to City via Gordon",
   "route_desc": "T1 North Shore Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "NTH_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T9",
   "route_long_name": "North Shore to Hornsby and Berowra via City",
   "route_desc": "T9 Northern Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "D11F2F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "NTH_1b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T9",
   "route_long_name": "North Shore to Hornsby and Berowra via City",
   "route_desc": "T9 Northern Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "D11F2F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "NTH_2a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T9",
   "route_long_name": "Berowra and Hornsby to North Shore via City",
   "route_desc": "T9 Northern Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "D11F2F",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "OLY_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T7",
   "route_long_name": "Central to Olympic Park",
   "route_desc": "T7 Olympic Park Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "6F818E",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "OLY_1b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T7",
   "route_long_name": "Olympic Park to Blacktown",
   "route_desc": "T7 Olympic Park Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "6F818E",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "OLY_2a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T7",
   "route_long_name": "Olympic Park to Central",
   "route_desc": "T7 Olympic Park Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "6F818E",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "OLY_2b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T7",
   "route_long_name": "Blacktown to Olympic Park",
   "route_desc": "T7 Olympic Park Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "6F818E",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "RTTA_DEF",
   "agency_id": "SydneyTrains",
   "route_short_name": "",
   "route_long_name": "Out Of Service",
   "route_desc": "Out Of Service trips",
   "route_type": 2,
   "route_url": "",
   "route_color": "888888",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "RTTA_REV",
   "agency_id": "SydneyTrains",
   "route_short_name": "",
   "route_long_name": "Non Revenue",
   "route_desc": "Non Revenue trips",
   "route_type": 2,
   "route_url": "",
   "route_color": "888888",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SCO_1a",
   "agency_id": "NSWTrains",
   "route_short_name": "SCO",
   "route_long_name": "Bondi Junction and Central to Bomaderry ",
   "route_desc": "South Coast Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SCO_1b",
   "agency_id": "NSWTrains",
   "route_short_name": "SCO",
   "route_long_name": "Bondi Junction and Central to Port Kembla",
   "route_desc": "South Coast Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SCO_2a",
   "agency_id": "NSWTrains",
   "route_short_name": "SCO",
   "route_long_name": "Bomaderry to Central and Bondi Junction",
   "route_desc": "South Coast Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SCO_2b",
   "agency_id": "NSWTrains",
   "route_short_name": "SCO",
   "route_long_name": "Port Kembla to Central and Bondi Junction",
   "route_desc": "South Coast Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "005AA3",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_1a",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Central to Campbelltown and Goulburn via Granville",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_1b",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Central to Campbelltown and Goulburn via Regents Park",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_1c",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Central to Campbelltown and Goulburn via Airport",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_1d",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Central to Campbelltown and Goulburn via East Hills and Sydenham",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_1e",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Campbelltown to Goulburn",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_2a",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Goulburn to Campbelltown and Central via Granville",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_2b",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Goulburn to Campbelltown and Central via Regents Park",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_2c",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Goulburn to Campbelltown and Central via Airport",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_2d",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Goulburn to Campbelltown and Central via East Hills and Sydenham",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "SHL_2e",
   "agency_id": "NSWTrains",
   "route_short_name": "SHL",
   "route_long_name": "Goulburn to Campbelltown",
   "route_desc": "Southern Highlands Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "00954C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "WST_1a",
   "agency_id": "SydneyTrains",
   "route_short_name": "T1",
   "route_long_name": "City to Emu Plains",
   "route_desc": "T1 Western Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "WST_1b",
   "agency_id": "SydneyTrains",
   "route_short_name": "T1",
   "route_long_name": "City to Richmond",
   "route_desc": "T1 Western Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "WST_2c",
   "agency_id": "SydneyTrains",
   "route_short_name": "T1",
   "route_long_name": "Emu Plains to City ",
   "route_desc": "T1 Western Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": "WST_2d",
   "agency_id": "SydneyTrains",
   "route_short_name": "T1",
   "route_long_name": "Richmond to City ",
   "route_desc": "T1 Western Line",
   "route_type": 2,
   "route_url": "",
   "route_color": "F99D1C",
   "route_text_color": "FFFFFF"
 }
]

export default ROUTES;
